version: '3.7'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./OLX-RSS:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:fpm
        volumes:
            - ./OLX-RSS:/code

